import type { AppState } from "./types.js";
import type { ServerSettings } from "../../../shared/types.js";

export const defaultVaultTimeoutMinutes = 5;
export const defaultReadingDefaults: ServerSettings["readingDefaults"] = {
  manga: { mode: "horizontal", fitting: "height", controlsVisible: false },
  manhwa: { mode: "vertical-scroll", fitting: "width", controlsVisible: false },
  book: { mode: "vertical-scroll", fitting: "height", controlsVisible: true },
  comic: { mode: "horizontal", fitting: "height", controlsVisible: false },
  lightNovel: { mode: "vertical-scroll", fitting: "height", controlsVisible: true },
  other: { mode: "vertical-scroll", fitting: "height", controlsVisible: false }
};

export const state: AppState = {
  user: null,
  libraries: [],
  personalLibraries: [],
  adminUsers: [],
  peopleUsers: [],
  contents: [],
  homeContents: [],
  readingNowContents: [],
  activeLibraryId: null,
  loadingLibraryId: null,
  libraryLoadError: "",
  activeSeriesId: null,
  activeView: "home",
  settingsSection: "server",
  serverSection: "libraries",
  accountMenuOpen: false,
  statsMenuOpen: false,
  openLibraryMenuId: null,
  vaultMenuOpen: false,
  openSeriesMenuId: null,
  openSeriesAddMenuId: null,
  openSeriesRemoveMenuId: null,
  libraryModalOpen: false,
  libraryModalError: "",
  editingLibraryId: null,
  collectionModalOpen: false,
  collectionModalError: "",
  collectionShareModalOpen: false,
  collectionShareError: "",
  collectionShareUsers: [],
  sharingCollectionId: null,
  deletingCollectionId: null,
  collectionDeleteError: "",
  editingCollectionId: null,
  collectionEditError: "",
  peopleShareError: "",
  activePeopleUserId: null,
  scanMessage: "",
  libraryModalStep: "general",
  libraryDraft: {
    name: "",
    kind: "manga",
    path: "",
    isPersonal: false
  },
  collectionDraft: {
    name: "",
    description: ""
  },
  collectionEditDraft: {
    name: "",
    description: ""
  },
  folderBrowser: null,
  sidebarCollapsed: true,
  mobileNavOpen: false,
  darkMode: localStorage.getItem("pugotiread-dark-mode") !== "light",
  search: "",
  progress: [],
  bookmarks: [],
  seriesMarks: [],
  wantToRead: [],
  readingList: [],
  collections: [],
  homeLayout: (localStorage.getItem("pugotiread-home-layout") === "list" ? "list" : "grid"),
  seriesChapterOrder: "asc",
  seriesChapterLayout: "list",
  seriesTab: "chapters",
  seriesReviews: {},
  profileReviews: [],
  seriesReviewError: "",
  profileEditing: false,
  profileError: "",
  profileFavoriteSearch: "",
  profilePasswordError: "",
  profilePasswordMessage: "",
  invitePathToken: null,
  inviteData: null,
  inviteError: "",
  inviteCreateAccountOpen: false,
  setupRequired: false,
  setupError: "",
  passwordResetOpen: false,
  passwordResetEmail: "",
  passwordResetMessage: "",
  passwordResetError: "",
  vaultUnlocked: false,
  vaultHiddenFromMenu: localStorage.getItem("pugotiread-vault-hidden") === "true",
  vaultToken: "",
  vaultError: "",
  vaultTimeoutMinutes: defaultVaultTimeoutMinutes,
  vaultSettingsDraft: String(defaultVaultTimeoutMinutes),
  vaultSettingsMessage: "",
  vaultSettingsError: "",
  readingSettingsDraft: structuredClone(defaultReadingDefaults),
  readingSettingsMessage: "",
  readingSettingsError: "",
  adminUserModalOpen: false,
  adminUserModalMode: "create",
  adminUserEditingId: null,
  adminUserDeleteId: null,
  adminUserModalError: "",
  adminUserInviteUrl: "",
  adminUserDraft: {
    email: "",
    displayName: "",
    username: "",
    password: "",
    role: "user",
    allowedLibraryIds: [],
    canLogin: true,
    canDownload: true,
    canChangePassword: true
  },
  reader: null
};
